driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.9
  - name: debian-8.2
  - name: fedora-22
  - name: fedora-23
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: windows-2008r2
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-2012r2
    driver_config:
      box: chef/windows-server-2012r2-standard

suites:
  - name: default
    run_list: aws::default
  - name: ohai_hint
    run_list: aws::ec2_hints
